# label ending_scenes:
#     if (lancaster_bad_flag):
#         jump lancaster_bad_ending
#     if (lancaster_good_flag):
#         jump lancaster_good_ending
#     if (lilith_bad_flag):
#         jump lilith_bad_ending
#     if (lilith_good_flag):
#         jump lilith_good_ending
#     if (lloyd_bad_flag):
#         jump lloyd_bad_ending
#     if (lloyd_neutral_flag):
#         jump lloyd_neutral_ending
#     if (lloyd_good_flag):
#         jump lloyd_good_ending